// prisma/seed.ts
// Comprehensive seed data for CampusCompass
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { hash } from "bcryptjs";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL || "file:./prisma/dev.db",
});
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 Seeding database...");

  // ─── Create Demo User ──────────────────────────────────
  const hashedPassword = await hash("password123", 12);
  const demoUser = await prisma.user.upsert({
    where: { email: "demo@campuscompass.in" },
    update: {},
    create: {
      name: "Demo User",
      email: "demo@campuscompass.in",
      password: hashedPassword,
    },
  });
  console.log("✅ Demo user created:", demoUser.email);

  // ─── Colleges Data ─────────────────────────────────────
  const colleges = [
    {
      name: "Indian Institute of Technology Bombay",
      slug: "iit-bombay",
      description: "Premier engineering institute known for cutting-edge research and world-class faculty.",
      longDescription: "IIT Bombay is one of India's most prestigious engineering institutions, established in 1958. Located in Powai, Mumbai, the institute has consistently ranked among the top engineering colleges in India and Asia. Known for its rigorous academic programs, state-of-the-art research facilities, and vibrant campus life, IIT Bombay produces some of the finest engineers, scientists, and entrepreneurs in the world. The campus spans over 550 acres of lush greenery with modern infrastructure including smart classrooms, advanced laboratories, and comprehensive sports facilities.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1d/Indian_Institute_of_Technology_Bombay_Logo.svg/330px-Indian_Institute_of_Technology_Bombay_Logo.svg.png",
      location: "Powai, Mumbai, Maharashtra",
      city: "Mumbai",
      state: "Maharashtra",
      rating: 4.8,
      totalReviews: 2340,
      feesMin: 200000,
      feesMax: 1500000,
      established: 1958,
      type: "IIT",
      accreditation: "NAAC A++",
      website: "https://www.iitb.ac.in",
      phone: "+91-22-25722545",
      email: "info@iitb.ac.in",
      ranking: 1,
      avgPackage: 2100000,
      highestPackage: 30000000,
      placementRate: 95.0,
      topRecruiters: "Google,Microsoft,Goldman Sachs,Apple,Amazon,Meta,McKinsey,BCG,JP Morgan,Adobe",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Research Labs,Swimming Pool,Gymnasium,Cafeteria,Medical Center,Auditorium",
      isFeatured: true,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 800000, seats: 120 },
        { name: "B.Tech Electrical Engineering", duration: "4 Years", fees: 800000, seats: 100 },
        { name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 800000, seats: 100 },
        { name: "M.Tech AI & Data Science", duration: "2 Years", fees: 400000, seats: 60 },
        { name: "MBA", duration: "2 Years", fees: 1500000, seats: 40 },
        { name: "PhD Computer Science", duration: "5 Years", fees: 200000, seats: 30 },
      ],
      reviews: [
        { rating: 5, title: "Best Engineering College in India", comment: "World-class faculty, amazing research opportunities, and incredible peer group. The campus placement record speaks for itself." },
        { rating: 4.5, title: "Transformative Experience", comment: "IIT Bombay changed my life. The exposure to cutting-edge technology and brilliant minds is unmatched." },
        { rating: 4.8, title: "Top-Notch Facilities", comment: "State-of-the-art labs, extensive library, and beautiful campus. Wouldn't trade this experience for anything." },
      ],
    },
    {
      name: "Indian Institute of Technology Delhi",
      slug: "iit-delhi",
      description: "Leading technology institute with exceptional research output and global industry connections.",
      longDescription: "IIT Delhi, established in 1961, stands as one of India's most prestigious institutions for higher education in engineering, technology, and sciences. Located in the heart of New Delhi at Hauz Khas, the institute boasts a sprawling 325-acre campus that houses world-class research centers, innovation hubs, and incubation facilities. IIT Delhi has produced numerous successful entrepreneurs, researchers, and industry leaders who have made significant contributions globally.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Indian_Institute_of_Technology_Delhi_Logo.svg/330px-Indian_Institute_of_Technology_Delhi_Logo.svg.png",
      location: "Hauz Khas, New Delhi",
      city: "New Delhi",
      state: "Delhi",
      rating: 4.7,
      totalReviews: 2100,
      feesMin: 200000,
      feesMax: 1400000,
      established: 1961,
      type: "IIT",
      accreditation: "NAAC A++",
      website: "https://home.iitd.ac.in",
      ranking: 2,
      avgPackage: 2000000,
      highestPackage: 28000000,
      placementRate: 93.0,
      topRecruiters: "Google,Microsoft,Samsung,Uber,Flipkart,Goldman Sachs,Morgan Stanley,Deloitte,Intel,Qualcomm",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Research Labs,Innovation Hub,Gymnasium,Cafeteria,Medical Center,Incubation Center",
      isFeatured: true,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 800000, seats: 110 },
        { name: "B.Tech Electrical Engineering", duration: "4 Years", fees: 800000, seats: 90 },
        { name: "M.Tech Machine Learning", duration: "2 Years", fees: 400000, seats: 50 },
        { name: "MBA", duration: "2 Years", fees: 1400000, seats: 35 },
      ],
      reviews: [
        { rating: 4.7, title: "Exceptional Learning Environment", comment: "The academic rigor and research opportunities are unparalleled. Great campus life too." },
        { rating: 4.5, title: "World-Class Research", comment: "IIT Delhi provides incredible research infrastructure and mentorship." },
      ],
    },
    {
      name: "Indian Institute of Technology Madras",
      slug: "iit-madras",
      description: "India's top-ranked institute known for innovation, research parks, and stellar placements.",
      longDescription: "IIT Madras, located in Chennai, Tamil Nadu, is consistently ranked as the No. 1 engineering institute in India. Founded in 1959 with German collaboration, the campus is set within a lush forest reserve spanning 617 acres. The institute is renowned for its Research Park — the first of its kind in India — and houses over 200 companies within its campus. IIT Madras leads in innovation, patents, and industry partnerships.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/6/69/IIT_Madras_Logo.svg/330px-IIT_Madras_Logo.svg.png",
      location: "Adyar, Chennai, Tamil Nadu",
      city: "Chennai",
      state: "Tamil Nadu",
      rating: 4.9,
      totalReviews: 2500,
      feesMin: 200000,
      feesMax: 1300000,
      established: 1959,
      type: "IIT",
      accreditation: "NAAC A++",
      website: "https://www.iitm.ac.in",
      ranking: 3,
      avgPackage: 2200000,
      highestPackage: 35000000,
      placementRate: 96.0,
      topRecruiters: "Google,Microsoft,Amazon,Cisco,Texas Instruments,Oracle,Samsung,Adobe,Qualcomm,Flipkart",
      facilities: "Library,Research Park,Sports Complex,Hostel,WiFi Campus,Deer Park,Swimming Pool,Gymnasium,Open Air Theatre,Medical Center",
      isFeatured: true,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 800000, seats: 130 },
        { name: "B.Tech Data Science", duration: "4 Years", fees: 800000, seats: 70 },
        { name: "B.Tech Aerospace Engineering", duration: "4 Years", fees: 800000, seats: 50 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 400000, seats: 60 },
        { name: "MBA", duration: "2 Years", fees: 1300000, seats: 40 },
      ],
      reviews: [
        { rating: 5, title: "No. 1 for a Reason", comment: "IIT Madras is simply the best. Research Park, forest campus, and top placements — it has everything." },
        { rating: 4.8, title: "Beautiful Campus", comment: "Living in a campus with deer and peacocks while studying cutting-edge tech is surreal." },
      ],
    },
    {
      name: "Indian Institute of Technology Kanpur",
      slug: "iit-kanpur",
      description: "Pioneer in computer science education in India with world-class aerospace and engineering programs.",
      longDescription: "IIT Kanpur was established in 1959 under the Indo-American Programme. It was the first institution in India to offer Computer Science education and continues to be a leader in the field. The 1000+ acre campus houses cutting-edge research facilities and is known for producing some of India's top tech entrepreneurs and academicians.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/IIT_Kanpur_Logo.svg/330px-IIT_Kanpur_Logo.svg.png",
      location: "Kalyanpur, Kanpur, Uttar Pradesh",
      city: "Kanpur",
      state: "Uttar Pradesh",
      rating: 4.6,
      totalReviews: 1800,
      feesMin: 200000,
      feesMax: 1200000,
      established: 1959,
      type: "IIT",
      accreditation: "NAAC A++",
      ranking: 4,
      avgPackage: 1800000,
      highestPackage: 25000000,
      placementRate: 90.0,
      topRecruiters: "Google,Microsoft,Samsung,Sprinklr,Goldman Sachs,Tower Research,DE Shaw,Flipkart,Uber,PayPal",
      facilities: "Library,Airstrip,Sports Complex,Hostel,WiFi Campus,Research Labs,Computer Center,Gymnasium,Medical Center,Guest House",
      isFeatured: true,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 800000, seats: 100 },
        { name: "B.Tech Aerospace Engineering", duration: "4 Years", fees: 800000, seats: 50 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 400000, seats: 50 },
      ],
      reviews: [
        { rating: 4.5, title: "CS Pioneer in India", comment: "IIT Kanpur started CS education in India. The legacy continues with excellent research." },
      ],
    },
    {
      name: "Indian Institute of Technology Kharagpur",
      slug: "iit-kharagpur",
      description: "India's first and largest IIT with a sprawling campus and the widest range of academic programs.",
      longDescription: "Founded in 1951, IIT Kharagpur is the oldest and largest IIT in India. Located in West Bengal, its massive 2100-acre campus is almost a self-sustained town. The institute offers the widest range of undergraduate, postgraduate, and doctoral programs among all IITs. Its alumni network is one of the strongest globally, with leaders in tech, business, academia, and government.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/IIT_Kharagpur_Logo.svg/330px-IIT_Kharagpur_Logo.svg.png",
      location: "Kharagpur, West Bengal",
      city: "Kharagpur",
      state: "West Bengal",
      rating: 4.5,
      totalReviews: 2000,
      feesMin: 200000,
      feesMax: 1200000,
      established: 1951,
      type: "IIT",
      accreditation: "NAAC A++",
      ranking: 5,
      avgPackage: 1700000,
      highestPackage: 22000000,
      placementRate: 88.0,
      topRecruiters: "Google,Microsoft,TCS,Infosys,Goldman Sachs,JP Morgan,Amazon,Cisco,Samsung,Accenture",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Technology Guest House,Hospital,Swimming Pool,Gymnasium,Netaji Auditorium,Temple",
      isFeatured: false,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 800000, seats: 90 },
        { name: "B.Tech Civil Engineering", duration: "4 Years", fees: 800000, seats: 80 },
        { name: "B.Tech Electrical Engineering", duration: "4 Years", fees: 800000, seats: 85 },
        { name: "B.Arch Architecture", duration: "5 Years", fees: 1000000, seats: 40 },
        { name: "MBA", duration: "2 Years", fees: 1200000, seats: 30 },
      ],
      reviews: [
        { rating: 4.5, title: "Legacy Institution", comment: "The oldest IIT with unmatched heritage. The campus is like a small town with everything you need." },
        { rating: 4.3, title: "Great for Research", comment: "Excellent research opportunities and diverse course offerings." },
      ],
    },
    {
      name: "BITS Pilani",
      slug: "bits-pilani",
      description: "India's premier private engineering university known for flexible academics and entrepreneur culture.",
      longDescription: "Birla Institute of Technology and Science (BITS) Pilani is one of India's top private engineering universities. Founded in 1964, the Pilani campus in Rajasthan is known for its unique academic flexibility, strong industry connect through the Practice School program, and vibrant student culture. BITS alumni have founded numerous successful startups and are leaders at top global companies.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/BITS_Pilani-Logo.svg/250px-BITS_Pilani-Logo.svg.png",
      location: "Pilani, Rajasthan",
      city: "Pilani",
      state: "Rajasthan",
      rating: 4.5,
      totalReviews: 1900,
      feesMin: 500000,
      feesMax: 2500000,
      established: 1964,
      type: "DEEMED",
      accreditation: "NAAC A",
      ranking: 6,
      avgPackage: 1600000,
      highestPackage: 20000000,
      placementRate: 85.0,
      topRecruiters: "Google,Microsoft,Goldman Sachs,Samsung,Flipkart,Uber,Sprinklr,American Express,JP Morgan,Deloitte",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Auditorium,Innovation Lab,Gymnasium,Cafeteria,Medical Center,Sky Watch Observatory",
      isFeatured: true,
      isTrending: false,
      courses: [
        { name: "B.E. Computer Science", duration: "4 Years", fees: 2000000, seats: 150 },
        { name: "B.E. Electronics", duration: "4 Years", fees: 2000000, seats: 120 },
        { name: "B.E. Mechanical Engineering", duration: "4 Years", fees: 2000000, seats: 100 },
        { name: "M.E. Software Systems", duration: "2 Years", fees: 800000, seats: 40 },
      ],
      reviews: [
        { rating: 4.6, title: "Freedom and Flexibility", comment: "BITS gives you the freedom to choose your path. The Practice School program is incredible for industry exposure." },
        { rating: 4.4, title: "Startup Culture", comment: "The entrepreneurial spirit here is contagious. Many successful startups have come out of BITS." },
      ],
    },
    {
      name: "National Institute of Technology Trichy",
      slug: "nit-trichy",
      description: "Top-ranked NIT known for strong academics, excellent placements, and vibrant campus culture.",
      longDescription: "NIT Trichy (NITT) is the top-ranked National Institute of Technology in India. Established in 1964 in Tiruchirappalli, Tamil Nadu, the institute has earned a reputation for academic excellence and strong placement records. The campus spans 800 acres and is known for its Pragyan tech fest and Festember cultural festival — among the largest in South India.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/National_Institute_of_Technology%2C_Tiruchirappalli.svg/330px-National_Institute_of_Technology%2C_Tiruchirappalli.svg.png",
      location: "Tiruchirappalli, Tamil Nadu",
      city: "Tiruchirappalli",
      state: "Tamil Nadu",
      rating: 4.3,
      totalReviews: 1400,
      feesMin: 150000,
      feesMax: 800000,
      established: 1964,
      type: "NIT",
      accreditation: "NAAC A+",
      ranking: 7,
      avgPackage: 1200000,
      highestPackage: 15000000,
      placementRate: 88.0,
      topRecruiters: "Microsoft,Amazon,Goldman Sachs,Flipkart,TCS,Infosys,Cognizant,Wipro,HCL,Samsung",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Computer Center,Gymnasium,Cafeteria,Medical Center,Central Workshop,Lecture Hall Complex",
      isFeatured: false,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 600000, seats: 80 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 600000, seats: 70 },
        { name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 600000, seats: 80 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 300000, seats: 30 },
      ],
      reviews: [
        { rating: 4.3, title: "Best NIT in India", comment: "NITT is consistently the top-ranked NIT. Great academics and placements." },
      ],
    },
    {
      name: "Delhi Technological University",
      slug: "dtu-delhi",
      description: "Leading state university in Delhi with strong industry connections and competitive placements.",
      longDescription: "Delhi Technological University (formerly DCE), established in 1941, is one of the oldest and most reputed engineering colleges in India. Located in Rohini, New Delhi, DTU has produced generations of successful engineers and entrepreneurs. The university offers a perfect blend of academics and extracurricular activities with its numerous student clubs and technical festivals.",
      image: "https://upload.wikimedia.org/wikipedia/en/b/b5/DTU%2C_Delhi_official_logo.png",
      location: "Rohini, New Delhi",
      city: "New Delhi",
      state: "Delhi",
      rating: 4.2,
      totalReviews: 1600,
      feesMin: 150000,
      feesMax: 700000,
      established: 1941,
      type: "PUBLIC",
      accreditation: "NAAC A+",
      ranking: 8,
      avgPackage: 1100000,
      highestPackage: 14000000,
      placementRate: 82.0,
      topRecruiters: "Google,Microsoft,Adobe,Samsung,Amazon,Deloitte,Goldman Sachs,ZS Associates,Sprinklr,Oracle",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Innovation Lab,Gymnasium,Cafeteria,Medical Center,Auditorium,Student Activity Center",
      isFeatured: false,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Engineering", duration: "4 Years", fees: 600000, seats: 150 },
        { name: "B.Tech Information Technology", duration: "4 Years", fees: 600000, seats: 120 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 600000, seats: 100 },
        { name: "MBA", duration: "2 Years", fees: 500000, seats: 60 },
      ],
      reviews: [
        { rating: 4.2, title: "Great Value for Money", comment: "DTU offers excellent education at government fees. The placement cell is very active." },
        { rating: 4.0, title: "Vibrant Campus Life", comment: "The fest culture and student clubs make DTU an amazing experience." },
      ],
    },
    {
      name: "Vellore Institute of Technology",
      slug: "vit-vellore",
      description: "Top private university known for excellent infrastructure, diverse student body, and strong placement record.",
      longDescription: "VIT Vellore is one of India's leading private engineering universities. Founded in 1984, VIT has grown to become a preferred destination for students across India and abroad. The university is known for its excellent infrastructure, diverse student community from over 60 countries, and consistent placement track record with top global companies. The campus features state-of-the-art labs and a technology business incubator.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Vellore_Institute_of_Technology_seal_2017.svg/250px-Vellore_Institute_of_Technology_seal_2017.svg.png",
      location: "Vellore, Tamil Nadu",
      city: "Vellore",
      state: "Tamil Nadu",
      rating: 4.1,
      totalReviews: 2200,
      feesMin: 300000,
      feesMax: 2000000,
      established: 1984,
      type: "PRIVATE",
      accreditation: "NAAC A++",
      ranking: 9,
      avgPackage: 900000,
      highestPackage: 12000000,
      placementRate: 80.0,
      topRecruiters: "Microsoft,Amazon,Infosys,TCS,Cognizant,Wipro,Deloitte,Capgemini,HCL,Zoho",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Swimming Pool,Gymnasium,Cafeteria,Medical Center,Auditorium,Technology Tower",
      isFeatured: true,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1800000, seats: 500 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 1600000, seats: 300 },
        { name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 1500000, seats: 250 },
        { name: "M.Tech Data Science", duration: "2 Years", fees: 600000, seats: 100 },
        { name: "MBA", duration: "2 Years", fees: 2000000, seats: 120 },
      ],
      reviews: [
        { rating: 4.0, title: "Good Private University", comment: "VIT provides excellent infrastructure and decent placements. The diversity of students is a plus." },
        { rating: 4.2, title: "Well-Maintained Campus", comment: "Clean campus, good food, and modern labs. Worth the fees." },
      ],
    },
    {
      name: "SRM Institute of Science and Technology",
      slug: "srm-chennai",
      description: "Leading private university with a massive campus, international collaborations, and diverse programs.",
      longDescription: "SRM IST is one of the top-ranked private universities in India. Located in Kattankulathur near Chennai, the campus spans over 250 acres and houses modern academic blocks, research centers, and student amenities. SRM is known for its international tie-ups with universities like MIT and Carnegie Mellon, offering students global exposure through semester exchange programs.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/SRM_Institute_of_Science_and_Technology_Logo.svg/960px-SRM_Institute_of_Science_and_Technology_Logo.svg.png",
      location: "Kattankulathur, Chennai, Tamil Nadu",
      city: "Chennai",
      state: "Tamil Nadu",
      rating: 3.9,
      totalReviews: 1800,
      feesMin: 300000,
      feesMax: 1800000,
      established: 1985,
      type: "PRIVATE",
      accreditation: "NAAC A++",
      ranking: 10,
      avgPackage: 750000,
      highestPackage: 10000000,
      placementRate: 78.0,
      topRecruiters: "Amazon,TCS,Infosys,Cognizant,Wipro,HCL,Accenture,Deloitte,Capgemini,IBM",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Swimming Pool,Gymnasium,Hospital,Auditorium,Incubation Center,Convention Center",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1500000, seats: 600 },
        { name: "B.Tech AI & ML", duration: "4 Years", fees: 1500000, seats: 200 },
        { name: "B.Tech Biomedical Engineering", duration: "4 Years", fees: 1200000, seats: 100 },
        { name: "MBBS", duration: "5.5 Years", fees: 1800000, seats: 250 },
      ],
      reviews: [
        { rating: 3.8, title: "Good for Exposure", comment: "SRM provides good international exposure through its exchange programs." },
      ],
    },
    {
      name: "Indian Institute of Science Bangalore",
      slug: "iisc-bangalore",
      description: "India's premier research institution with Nobel-caliber research and PhD programs.",
      longDescription: "IISc Bangalore, founded in 1909 by Jamsetji Tata, is India's foremost research institution. Located on a 400-acre campus in the heart of Bangalore, IISc is known for its groundbreaking research in science, engineering, and interdisciplinary studies. The institute has the highest research output per capita among Indian institutions and houses several Centers of Excellence funded by the Government of India.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=iisc-bangalore",
      location: "Malleshwaram, Bangalore, Karnataka",
      city: "Bangalore",
      state: "Karnataka",
      rating: 4.9,
      totalReviews: 1200,
      feesMin: 100000,
      feesMax: 500000,
      established: 1909,
      type: "PUBLIC",
      accreditation: "NAAC A++",
      ranking: 11,
      avgPackage: 2500000,
      highestPackage: 40000000,
      placementRate: 92.0,
      topRecruiters: "Google,Microsoft,Apple,Intel,NVIDIA,Qualcomm,Samsung,ISRO,DRDO,BARC",
      facilities: "Library,Research Centers,Hostel,WiFi Campus,Botanical Garden,Gymnasium,Cafeteria,Medical Center,J.N. Tata Auditorium,Supercomputing Facility",
      isFeatured: true,
      isTrending: true,
      courses: [
        { name: "B.S. Research Program", duration: "4 Years", fees: 200000, seats: 120 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 200000, seats: 40 },
        { name: "M.Tech AI", duration: "2 Years", fees: 200000, seats: 30 },
        { name: "PhD Computer Science", duration: "5 Years", fees: 100000, seats: 50 },
        { name: "PhD Physics", duration: "5 Years", fees: 100000, seats: 40 },
      ],
      reviews: [
        { rating: 5.0, title: "Research Paradise", comment: "IISc is the best place for research in India. Period." },
        { rating: 4.8, title: "World-Class Faculty", comment: "The faculty here are world-renowned. Getting to learn from them is a privilege." },
      ],
    },
    {
      name: "NIT Warangal",
      slug: "nit-warangal",
      description: "One of India's top NITs with strong alumni network and excellent placement track record.",
      longDescription: "NIT Warangal, established in 1959, is one of the first National Institutes of Technology in India. Located in Telangana, the institute has a rich history of academic excellence and has produced successful engineers across the globe. Known for its TechnoZion tech fest and strong alumni network in top tech companies.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=nit-warangal",
      location: "Warangal, Telangana",
      city: "Warangal",
      state: "Telangana",
      rating: 4.2,
      totalReviews: 1300,
      feesMin: 150000,
      feesMax: 700000,
      established: 1959,
      type: "NIT",
      accreditation: "NAAC A+",
      ranking: 12,
      avgPackage: 1100000,
      highestPackage: 13000000,
      placementRate: 85.0,
      topRecruiters: "Microsoft,Amazon,Google,Samsung,Goldman Sachs,Flipkart,TCS,Infosys,Adobe,Oracle",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Computer Center,Gymnasium,Cafeteria,Medical Center,Seminar Hall,Guest House",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 600000, seats: 80 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 600000, seats: 70 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 250000, seats: 25 },
      ],
      reviews: [
        { rating: 4.2, title: "Strong Alumni Network", comment: "NITW alumni are everywhere in top companies. The network is incredibly helpful." },
      ],
    },
    {
      name: "IIIT Hyderabad",
      slug: "iiit-hyderabad",
      description: "India's top IIIT specialized in computer science, AI research, and technology innovation.",
      longDescription: "IIIT Hyderabad is India's premier research-focused institution specializing in Information Technology, Computer Science, and related fields. Known for its research-oriented approach with labs in AI, Machine Learning, Computer Vision, NLP, and Robotics. The institute follows a unique research-centric curriculum that prepares students for both industry and academia.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=iiit-hyderabad",
      location: "Gachibowli, Hyderabad, Telangana",
      city: "Hyderabad",
      state: "Telangana",
      rating: 4.6,
      totalReviews: 900,
      feesMin: 300000,
      feesMax: 1200000,
      established: 1998,
      type: "IIIT",
      accreditation: "NAAC A+",
      ranking: 13,
      avgPackage: 1800000,
      highestPackage: 25000000,
      placementRate: 95.0,
      topRecruiters: "Google,Microsoft,Amazon,Apple,Meta,Uber,Flipkart,Tower Research,DE Shaw,Goldman Sachs",
      facilities: "Library,Research Labs,Hostel,WiFi Campus,Innovation Center,Gymnasium,Cafeteria,Medical Center,Vindhya Convention Center,Felicity Ground",
      isFeatured: true,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1000000, seats: 200 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 1000000, seats: 100 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 500000, seats: 60 },
        { name: "MS by Research", duration: "2 Years", fees: 400000, seats: 50 },
        { name: "PhD", duration: "5 Years", fees: 300000, seats: 40 },
      ],
      reviews: [
        { rating: 4.7, title: "AI Research Hub", comment: "IIIT-H is the best place in India for AI and ML research. The labs are world-class." },
        { rating: 4.5, title: "Research-First Approach", comment: "The research-oriented curriculum sets you up perfectly for cutting-edge work." },
      ],
    },
    {
      name: "Manipal Institute of Technology",
      slug: "mit-manipal",
      description: "Premium private engineering college in a university town with global exposure and vibrant campus life.",
      longDescription: "Manipal Institute of Technology, part of Manipal Academy of Higher Education, is one of India's most sought-after private engineering colleges. Located in the university town of Manipal, Karnataka, the institute offers a unique collegiate experience with students from across India and over 50 countries. Known for its excellent infrastructure, MIT Manipal emphasizes holistic development with a strong focus on innovation and entrepreneurship.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=mit-manipal",
      location: "Manipal, Karnataka",
      city: "Manipal",
      state: "Karnataka",
      rating: 4.0,
      totalReviews: 1700,
      feesMin: 400000,
      feesMax: 2200000,
      established: 1957,
      type: "PRIVATE",
      accreditation: "NAAC A++",
      ranking: 14,
      avgPackage: 800000,
      highestPackage: 10000000,
      placementRate: 75.0,
      topRecruiters: "Amazon,Microsoft,Goldman Sachs,Deloitte,TCS,Infosys,Wipro,Samsung,Oracle,Cisco",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Swimming Pool,Gymnasium,Innovation Center,Medical Center,Auditorium,Student Plaza",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1800000, seats: 300 },
        { name: "B.Tech Information Technology", duration: "4 Years", fees: 1700000, seats: 200 },
        { name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 1600000, seats: 150 },
      ],
      reviews: [
        { rating: 4.0, title: "University Town Experience", comment: "Living in Manipal is an experience in itself. The campus life is incredible." },
        { rating: 4.1, title: "Global Exposure", comment: "Students from 50+ countries create a truly diverse environment." },
      ],
    },
    {
      name: "College of Engineering Pune",
      slug: "coep-pune",
      description: "One of Asia's oldest engineering colleges with a rich heritage and strong academic tradition.",
      longDescription: "COEP Technological University, established in 1854, is one of the oldest engineering colleges in Asia. Located on the banks of the Mula-Mutha river in Pune, the campus blends colonial-era architecture with modern facilities. COEP is known for its strong academic traditions, competitive admissions, and the Mindspark tech festival.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=coep-pune",
      location: "Shivajinagar, Pune, Maharashtra",
      city: "Pune",
      state: "Maharashtra",
      rating: 4.1,
      totalReviews: 1100,
      feesMin: 100000,
      feesMax: 500000,
      established: 1854,
      type: "PUBLIC",
      accreditation: "NAAC A",
      ranking: 15,
      avgPackage: 900000,
      highestPackage: 11000000,
      placementRate: 80.0,
      topRecruiters: "Google,Microsoft,Amazon,Persistent Systems,Infosys,TCS,Cummins,ThoughtWorks,Barclays,Morgan Stanley",
      facilities: "Library,Sports Ground,Hostel,WiFi Campus,Heritage Building,Gymnasium,Cafeteria,Medical Center,Boat Club,Workshop",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Engineering", duration: "4 Years", fees: 400000, seats: 100 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 400000, seats: 80 },
        { name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 400000, seats: 90 },
        { name: "M.Tech Computer Engineering", duration: "2 Years", fees: 200000, seats: 20 },
      ],
      reviews: [
        { rating: 4.1, title: "Historic Institution", comment: "170 years of engineering excellence. The heritage adds to the experience." },
      ],
    },
    {
      name: "Indian Institute of Technology Roorkee",
      slug: "iit-roorkee",
      description: "Historic IIT with expertise in civil and architectural engineering, established in 1847.",
      longDescription: "IIT Roorkee is one of the world's oldest technical institutions, originally established as the Roorkee Engineering College in 1847. Given IIT status in 2001, the institute in Uttarakhand is known for its strong civil, architectural, and environmental engineering programs. The picturesque campus near the Ganges canal provides a serene academic environment.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=iit-roorkee",
      location: "Roorkee, Uttarakhand",
      city: "Roorkee",
      state: "Uttarakhand",
      rating: 4.4,
      totalReviews: 1500,
      feesMin: 200000,
      feesMax: 1200000,
      established: 1847,
      type: "IIT",
      accreditation: "NAAC A++",
      ranking: 16,
      avgPackage: 1600000,
      highestPackage: 20000000,
      placementRate: 87.0,
      topRecruiters: "Google,Microsoft,Samsung,Amazon,Uber,Goldman Sachs,JP Morgan,Adobe,Oracle,TCS",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Ganges Canal,Swimming Pool,Gymnasium,Medical Center,Convocation Hall,Observatory",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 800000, seats: 80 },
        { name: "B.Tech Civil Engineering", duration: "4 Years", fees: 800000, seats: 100 },
        { name: "B.Arch Architecture", duration: "5 Years", fees: 1000000, seats: 40 },
        { name: "M.Tech Structural Engineering", duration: "2 Years", fees: 400000, seats: 30 },
      ],
      reviews: [
        { rating: 4.4, title: "Heritage Meets Modernity", comment: "One of the oldest tech institutions in the world, now with modern facilities and strong placements." },
      ],
    },
    {
      name: "Jadavpur University",
      slug: "jadavpur-university",
      description: "Premier public university in Kolkata known for affordable education and strong engineering programs.",
      longDescription: "Jadavpur University, established in 1955 in Kolkata, is one of the most prestigious public universities in India. Known for its affordable yet high-quality education, the university attracts top students from across the country. The engineering faculty is particularly renowned, with competitive admission comparable to top NITs.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=jadavpur-university",
      location: "Jadavpur, Kolkata, West Bengal",
      city: "Kolkata",
      state: "West Bengal",
      rating: 4.2,
      totalReviews: 1400,
      feesMin: 50000,
      feesMax: 300000,
      established: 1955,
      type: "PUBLIC",
      accreditation: "NAAC A",
      ranking: 17,
      avgPackage: 800000,
      highestPackage: 8000000,
      placementRate: 75.0,
      topRecruiters: "TCS,Infosys,Cognizant,Wipro,Amazon,Microsoft,Google,Deloitte,Accenture,IBM",
      facilities: "Library,Sports Ground,Hostel,WiFi Campus,Research Labs,Gymnasium,Cafeteria,Medical Center,Auditorium,Central Library",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.E. Computer Science", duration: "4 Years", fees: 200000, seats: 80 },
        { name: "B.E. Electronics", duration: "4 Years", fees: 200000, seats: 70 },
        { name: "B.E. Mechanical Engineering", duration: "4 Years", fees: 200000, seats: 80 },
        { name: "M.E. Computer Science", duration: "2 Years", fees: 100000, seats: 25 },
      ],
      reviews: [
        { rating: 4.3, title: "Best Value Education", comment: "World-class education at minimal fees. JU is truly a gem." },
      ],
    },
    {
      name: "NIT Surathkal",
      slug: "nit-surathkal",
      description: "Scenic beachside NIT known for strong CS department and excellent placement record.",
      longDescription: "NIT Karnataka (Surathkal), established in 1960, is one of the top-ranked NITs in India. Located on the shores of the Arabian Sea near Mangalore, the campus offers a unique beachside engineering experience. NITK is known for its strong computer science department and consistently good placement statistics.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=nit-surathkal",
      location: "Surathkal, Karnataka",
      city: "Mangalore",
      state: "Karnataka",
      rating: 4.3,
      totalReviews: 1200,
      feesMin: 150000,
      feesMax: 700000,
      established: 1960,
      type: "NIT",
      accreditation: "NAAC A+",
      ranking: 18,
      avgPackage: 1100000,
      highestPackage: 14000000,
      placementRate: 86.0,
      topRecruiters: "Google,Microsoft,Amazon,Samsung,Goldman Sachs,Flipkart,Oracle,Cisco,Intel,Adobe",
      facilities: "Library,Beach,Sports Complex,Hostel,WiFi Campus,Swimming Pool,Gymnasium,Cafeteria,Medical Center,Auditorium",
      isFeatured: false,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 600000, seats: 80 },
        { name: "B.Tech Information Technology", duration: "4 Years", fees: 600000, seats: 70 },
        { name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 600000, seats: 75 },
      ],
      reviews: [
        { rating: 4.3, title: "Beach Campus", comment: "Studying with a beach on campus is an experience like no other. Academics are excellent too." },
      ],
    },
    {
      name: "Thapar Institute of Engineering and Technology",
      slug: "thapar-patiala",
      description: "Top private engineering institute in North India with strong industry ties and modern infrastructure.",
      longDescription: "Thapar Institute of Engineering and Technology, established in 1956 in Patiala, Punjab, is one of North India's premier engineering institutions. The institute is known for its rigorous academics, modern campus infrastructure, and strong placement record. Thapar has collaborated with several international universities for student and faculty exchange programs.",
      image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80&sig=thapar-patiala",
      location: "Patiala, Punjab",
      city: "Patiala",
      state: "Punjab",
      rating: 4.0,
      totalReviews: 1300,
      feesMin: 400000,
      feesMax: 1800000,
      established: 1956,
      type: "DEEMED",
      accreditation: "NAAC A",
      ranking: 19,
      avgPackage: 800000,
      highestPackage: 9000000,
      placementRate: 78.0,
      topRecruiters: "Amazon,Microsoft,Samsung,TCS,Infosys,Wipro,Deloitte,Cognizant,HCL,Accenture",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Swimming Pool,Gymnasium,Cafeteria,Medical Center,Auditorium,Technology Lab",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.E. Computer Engineering", duration: "4 Years", fees: 1500000, seats: 200 },
        { name: "B.E. Electronics", duration: "4 Years", fees: 1400000, seats: 120 },
        { name: "B.E. Mechanical Engineering", duration: "4 Years", fees: 1300000, seats: 100 },
      ],
      reviews: [
        { rating: 4.0, title: "Strong Academics", comment: "Thapar has a rigorous academic system that prepares you well for the industry." },
      ],
    },
    {
      name: "Indian Statistical Institute Kolkata",
      slug: "isi-kolkata",
      description: "World-renowned institute for statistics, mathematics, and computer science with legendary faculty.",
      longDescription: "ISI Kolkata, founded by P.C. Mahalanobis in 1931, is a world-renowned institute for statistics, data science, and applied mathematics. The institute has produced several world-class statisticians and computer scientists. Its B.Stat and B.Math programs are considered among the toughest to get into in India.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/Indianstatisticalinstitutelogo.svg/330px-Indianstatisticalinstitutelogo.svg.png",
      location: "Baranagar, Kolkata, West Bengal",
      city: "Kolkata",
      state: "West Bengal",
      rating: 4.7,
      totalReviews: 600,
      feesMin: 50000,
      feesMax: 200000,
      established: 1931,
      type: "PUBLIC",
      accreditation: "NAAC A+",
      ranking: 20,
      avgPackage: 2000000,
      highestPackage: 30000000,
      placementRate: 92.0,
      topRecruiters: "Google,Microsoft,Goldman Sachs,DE Shaw,Tower Research,Citadel,Optiver,Amazon,Meta,Apple",
      facilities: "Library,Research Labs,Hostel,WiFi Campus,Computer Labs,Gymnasium,Cafeteria,Medical Center,Seminar Hall,Garden",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Stat (Hons)", duration: "3 Years", fees: 60000, seats: 50 },
        { name: "B.Math (Hons)", duration: "3 Years", fees: 60000, seats: 50 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 100000, seats: 30 },
        { name: "M.Stat", duration: "2 Years", fees: 80000, seats: 60 },
      ],
      reviews: [
        { rating: 4.8, title: "Legendary for Stats & Math", comment: "If you love math and stats, ISI is heaven. The faculty are world-class." },
      ],
    },
    {
      name: "PES University",
      slug: "pes-bangalore",
      description: "Fast-growing private university in Bangalore known for tech programs and startup ecosystem.",
      longDescription: "PES University, located in Bangalore's tech corridor, has quickly risen to become one of South India's most sought-after private universities. Known for its strong CS programs and proximity to the IT industry, PES produces job-ready graduates with practical industry skills. The university's incubation center has spawned several successful startups.",
      image: "https://upload.wikimedia.org/wikipedia/en/9/9e/PES-University-Bangalore.png",
      location: "Banashankari, Bangalore, Karnataka",
      city: "Bangalore",
      state: "Karnataka",
      rating: 4.0,
      totalReviews: 1100,
      feesMin: 400000,
      feesMax: 2000000,
      established: 1988,
      type: "PRIVATE",
      accreditation: "NAAC A+",
      ranking: 21,
      avgPackage: 900000,
      highestPackage: 12000000,
      placementRate: 80.0,
      topRecruiters: "Amazon,Microsoft,Google,Flipkart,Cisco,Oracle,Samsung,Adobe,VMware,ServiceNow",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Innovation Center,Gymnasium,Cafeteria,Medical Center,Auditorium,Startup Hub",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1600000, seats: 300 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 1500000, seats: 150 },
        { name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 1400000, seats: 120 },
        { name: "MBA", duration: "2 Years", fees: 2000000, seats: 120 },
      ],
      reviews: [
        { rating: 4.0, title: "Great for Tech", comment: "Being in Bangalore gives PES students a huge advantage for tech careers." },
      ],
    },
    {
      name: "IIT Guwahati",
      slug: "iit-guwahati",
      description: "Modern IIT with a stunning lakeside campus in Northeast India and growing research output.",
      longDescription: "IIT Guwahati, established in 1994, is one of the newer IITs that has quickly risen in prominence. Located on the banks of the Brahmaputra river in Assam, its 700-acre campus is one of the most beautiful among IITs. The institute has a strong research culture with departments in emerging areas like nanotechnology and biosciences.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/IIT_Guwahati_Logo.svg/330px-IIT_Guwahati_Logo.svg.png",
      location: "North Guwahati, Assam",
      city: "Guwahati",
      state: "Assam",
      rating: 4.4,
      totalReviews: 1100,
      feesMin: 200000,
      feesMax: 1200000,
      established: 1994,
      type: "IIT",
      accreditation: "NAAC A++",
      ranking: 22,
      avgPackage: 1500000,
      highestPackage: 18000000,
      placementRate: 85.0,
      topRecruiters: "Google,Microsoft,Amazon,Samsung,Goldman Sachs,Flipkart,Adobe,Oracle,Uber,PayPal",
      facilities: "Library,Brahmaputra View,Sports Complex,Hostel,WiFi Campus,Lake,Gymnasium,Cafeteria,Medical Center,Auditorium",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 800000, seats: 80 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 800000, seats: 70 },
        { name: "B.Des Design", duration: "4 Years", fees: 800000, seats: 30 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 400000, seats: 40 },
      ],
      reviews: [
        { rating: 4.5, title: "Most Beautiful IIT", comment: "The campus by the Brahmaputra is breathtaking. Academics and placements are equally impressive." },
      ],
    },
    {
      name: "Amity University Noida",
      slug: "amity-noida",
      description: "Massive private university with 200+ programs and strong international university partnerships.",
      longDescription: "Amity University Noida is one of India's largest private universities, offering over 200 programs across 14 faculties. The sprawling campus in Noida features modern infrastructure including smart classrooms, labs, and a state-of-the-art sports complex. Amity has partnerships with over 100 international universities for exchange programs and joint degrees.",
      image: "https://upload.wikimedia.org/wikipedia/en/f/ff/Amity_University_logo.png",
      location: "Sector 125, Noida, Uttar Pradesh",
      city: "Noida",
      state: "Uttar Pradesh",
      rating: 3.5,
      totalReviews: 2000,
      feesMin: 300000,
      feesMax: 2500000,
      established: 2005,
      type: "PRIVATE",
      accreditation: "NAAC A+",
      ranking: 23,
      avgPackage: 500000,
      highestPackage: 5000000,
      placementRate: 65.0,
      topRecruiters: "TCS,Infosys,Wipro,Cognizant,HCL,Accenture,Capgemini,IBM,Deloitte,EY",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Swimming Pool,Gymnasium,Cafeteria,Medical Center,Amphitheatre,Media Center",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1200000, seats: 500 },
        { name: "BBA", duration: "3 Years", fees: 900000, seats: 300 },
        { name: "B.Des", duration: "4 Years", fees: 1000000, seats: 100 },
        { name: "MBA", duration: "2 Years", fees: 2500000, seats: 200 },
      ],
      reviews: [
        { rating: 3.5, title: "Big Campus, Decent Quality", comment: "Amity has impressive infrastructure but academic quality varies by department." },
      ],
    },
    {
      name: "IIT Hyderabad",
      slug: "iit-hyderabad",
      description: "New-generation IIT with interdisciplinary focus and strong AI/ML research programs.",
      longDescription: "IIT Hyderabad, established in 2008, is one of the second-generation IITs that has quickly established itself as a research powerhouse. Located in Kandi, Telangana, the institute is known for its interdisciplinary approach and strong focus on AI, Machine Learning, and Biomedical Engineering. The campus features modern architecture and sustainable design.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/19/IIT_Hyderabad_Insignia.svg/330px-IIT_Hyderabad_Insignia.svg.png",
      location: "Kandi, Sangareddy, Telangana",
      city: "Hyderabad",
      state: "Telangana",
      rating: 4.3,
      totalReviews: 800,
      feesMin: 200000,
      feesMax: 1200000,
      established: 2008,
      type: "IIT",
      accreditation: "NAAC A++",
      ranking: 24,
      avgPackage: 1400000,
      highestPackage: 17000000,
      placementRate: 85.0,
      topRecruiters: "Google,Microsoft,Amazon,Samsung,Flipkart,Goldman Sachs,JP Morgan,Adobe,Oracle,Intel",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Research Park,Gymnasium,Cafeteria,Medical Center,Lecture Hall Complex,Maker Space",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 800000, seats: 80 },
        { name: "B.Tech AI", duration: "4 Years", fees: 800000, seats: 40 },
        { name: "B.Tech Biomedical Engineering", duration: "4 Years", fees: 800000, seats: 30 },
        { name: "M.Tech AI & ML", duration: "2 Years", fees: 400000, seats: 30 },
      ],
      reviews: [
        { rating: 4.3, title: "Rising Star", comment: "IIT Hyderabad is growing fast with excellent AI/ML programs and modern infrastructure." },
      ],
    },
    {
      name: "Christ University Bangalore",
      slug: "christ-university",
      description: "Prestigious private university known for management programs, campus discipline, and holistic education.",
      longDescription: "Christ University, Bangalore, established in 1969, is one of India's top private universities known for academic excellence and holistic development. Originally focused on arts and science, Christ has expanded to include engineering, management, law, and social sciences. The university is known for its disciplined campus environment, strong focus on ethics, and consistent placement records.",
      image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Christ_University_Official_Logo.png",
      location: "Hosur Road, Bangalore, Karnataka",
      city: "Bangalore",
      state: "Karnataka",
      rating: 4.0,
      totalReviews: 1600,
      feesMin: 200000,
      feesMax: 1500000,
      established: 1969,
      type: "DEEMED",
      accreditation: "NAAC A++",
      ranking: 25,
      avgPackage: 700000,
      highestPackage: 7000000,
      placementRate: 78.0,
      topRecruiters: "Deloitte,EY,KPMG,PwC,Amazon,Infosys,TCS,Wipro,Goldman Sachs,JP Morgan",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Auditorium,Gymnasium,Cafeteria,Medical Center,Chapel,Student Center",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "BBA", duration: "3 Years", fees: 600000, seats: 200 },
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1200000, seats: 100 },
        { name: "BCA", duration: "3 Years", fees: 400000, seats: 150 },
        { name: "MBA", duration: "2 Years", fees: 1500000, seats: 200 },
        { name: "LLB", duration: "5 Years", fees: 1000000, seats: 100 },
      ],
      reviews: [
        { rating: 4.0, title: "Disciplined Environment", comment: "Christ provides a well-structured and disciplined learning environment. Great for BBA/MBA." },
      ],
    },
    {
      name: "NIT Calicut",
      slug: "nit-calicut",
      description: "Leading NIT in Kerala with strong academics and a beautiful campus near the coast.",
      longDescription: "NIT Calicut, established in 1961 in Kozhikode, Kerala, is one of the premier NITs known for its scenic campus and strong academic programs. The institute sits atop a hill near Chathamangalam, surrounded by lush greenery. NITC is especially known for its Computer Science and Electronics departments.",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Correct_Logo_of_NIT_Calicut.svg/330px-Correct_Logo_of_NIT_Calicut.svg.png",
      location: "Chathamangalam, Kozhikode, Kerala",
      city: "Kozhikode",
      state: "Kerala",
      rating: 4.1,
      totalReviews: 1000,
      feesMin: 150000,
      feesMax: 600000,
      established: 1961,
      type: "NIT",
      accreditation: "NAAC A",
      ranking: 26,
      avgPackage: 900000,
      highestPackage: 11000000,
      placementRate: 80.0,
      topRecruiters: "Google,Microsoft,Amazon,TCS,Infosys,Oracle,Samsung,Cisco,Deloitte,Cognizant",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Hilltop Campus,Gymnasium,Cafeteria,Medical Center,Auditorium,Computer Center",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 500000, seats: 70 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 500000, seats: 65 },
        { name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 500000, seats: 70 },
      ],
      reviews: [
        { rating: 4.1, title: "Scenic Campus", comment: "NITC's hilltop campus is one of the most beautiful among NITs." },
      ],
    },
    {
      name: "LNM Institute of Information Technology",
      slug: "lnmiit-jaipur",
      description: "Well-funded private CS-focused institute in Jaipur backed by the Lakshmi Niwas Mittal Foundation.",
      longDescription: "LNMIIT, established in 2003 and supported by the L.N. Mittal Foundation, is a focused institution emphasizing information technology and computer science. Located in Jaipur, Rajasthan, the institute offers a tight-knit academic community with a low student-to-faculty ratio and modern facilities. Known for producing strong CS graduates who land roles at top tech companies.",
      image: "https://upload.wikimedia.org/wikipedia/commons/4/41/East_facade_Hawa_Mahal_Jaipur_from_ground_level_%28July_2022%29_-_img_01.jpg",
      location: "Rupa ki Nangal, Jaipur, Rajasthan",
      city: "Jaipur",
      state: "Rajasthan",
      rating: 3.8,
      totalReviews: 600,
      feesMin: 300000,
      feesMax: 1500000,
      established: 2003,
      type: "PRIVATE",
      accreditation: "NAAC A",
      ranking: 27,
      avgPackage: 700000,
      highestPackage: 8000000,
      placementRate: 72.0,
      topRecruiters: "Amazon,Microsoft,Samsung,Goldman Sachs,Flipkart,TCS,Infosys,Wipro,Cognizant,Oracle",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Computer Labs,Gymnasium,Cafeteria,Medical Center,Auditorium,Open Air Theatre",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1200000, seats: 120 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 1200000, seats: 60 },
        { name: "B.Tech Computer & Communication", duration: "4 Years", fees: 1200000, seats: 60 },
      ],
      reviews: [
        { rating: 3.8, title: "CS Focused", comment: "Great for CS students. Small batch size means more individual attention." },
      ],
    },
    {
      name: "Anna University",
      slug: "anna-university",
      description: "Top state technical university in Chennai offering high-quality affordable engineering education.",
      longDescription: "Anna University, established in 1978 in Chennai, is one of India's top technical universities. Named after C.N. Annadurai, the university campus in Guindy covers over 100 acres and houses several constituent colleges. Anna University is the examining body for hundreds of engineering colleges across Tamil Nadu and is known for its affordable, high-quality technical education.",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Anna_university_01.jpg/3840px-Anna_university_01.jpg",
      location: "Guindy, Chennai, Tamil Nadu",
      city: "Chennai",
      state: "Tamil Nadu",
      rating: 4.0,
      totalReviews: 1500,
      feesMin: 100000,
      feesMax: 500000,
      established: 1978,
      type: "PUBLIC",
      accreditation: "NAAC A+",
      ranking: 28,
      avgPackage: 700000,
      highestPackage: 8000000,
      placementRate: 75.0,
      topRecruiters: "TCS,Infosys,Cognizant,Wipro,HCL,Amazon,Zoho,Freshworks,Accenture,Capgemini",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Guindy National Park,Gymnasium,Cafeteria,Medical Center,Convention Center,Workshop",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.E. Computer Science", duration: "4 Years", fees: 300000, seats: 120 },
        { name: "B.E. Electronics", duration: "4 Years", fees: 300000, seats: 100 },
        { name: "B.E. Mechanical Engineering", duration: "4 Years", fees: 300000, seats: 100 },
        { name: "M.E. Computer Science", duration: "2 Years", fees: 150000, seats: 30 },
      ],
      reviews: [
        { rating: 4.0, title: "Affordable Excellence", comment: "Anna University provides excellent education at very affordable fees. The campus in Guindy is beautiful." },
      ],
    },
    {
      name: "Shiv Nadar University",
      slug: "shiv-nadar-university",
      description: "Young, research-driven private university backed by the HCL founder with world-class facilities.",
      longDescription: "Shiv Nadar University, founded in 2011 by Shiv Nadar (founder of HCL Technologies), is a multidisciplinary research university in Greater Noida, Uttar Pradesh. Despite being relatively young, SNU has quickly gained recognition for its research output, international faculty, and state-of-the-art infrastructure. The university follows a liberal arts approach to engineering education.",
      image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Snumaingate.jpg",
      location: "Dadri, Greater Noida, Uttar Pradesh",
      city: "Greater Noida",
      state: "Uttar Pradesh",
      rating: 4.1,
      totalReviews: 700,
      feesMin: 400000,
      feesMax: 2200000,
      established: 2011,
      type: "PRIVATE",
      accreditation: "NAAC A",
      ranking: 29,
      avgPackage: 1000000,
      highestPackage: 13000000,
      placementRate: 80.0,
      topRecruiters: "Microsoft,Amazon,Google,Adobe,Samsung,Goldman Sachs,Deloitte,Sprinklr,HCL,Oracle",
      facilities: "Library,Sports Complex,Hostel,WiFi Campus,Research Labs,Swimming Pool,Gymnasium,Cafeteria,Medical Center,Art Gallery",
      isFeatured: false,
      isTrending: false,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 1800000, seats: 120 },
        { name: "B.Tech Data Science", duration: "4 Years", fees: 1800000, seats: 60 },
        { name: "B.Tech Electronics", duration: "4 Years", fees: 1700000, seats: 80 },
        { name: "MBA", duration: "2 Years", fees: 2200000, seats: 60 },
      ],
      reviews: [
        { rating: 4.1, title: "Modern Campus, Great Faculty", comment: "SNU has some of the best infrastructure among private universities. Faculty from top global universities." },
      ],
    },
    {
      name: "IIIT Delhi",
      slug: "iiit-delhi",
      description: "State IIIT in Delhi known for strong CS programs, AI research, and competitive placements.",
      longDescription: "Indraprastha Institute of Information Technology Delhi (IIIT-D), established in 2008, is a state university focused on IT and interdisciplinary education. Located in Okhla, New Delhi, IIIT-D has quickly become one of the top computer science institutes in India. The institute is known for its research in AI, Machine Learning, mobile computing, and cybersecurity.",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/IIITD_Campus_2024.jpg/3840px-IIITD_Campus_2024.jpg",
      location: "Okhla, New Delhi",
      city: "New Delhi",
      state: "Delhi",
      rating: 4.4,
      totalReviews: 800,
      feesMin: 300000,
      feesMax: 1200000,
      established: 2008,
      type: "IIIT",
      accreditation: "NAAC A+",
      ranking: 30,
      avgPackage: 1500000,
      highestPackage: 20000000,
      placementRate: 90.0,
      topRecruiters: "Google,Microsoft,Amazon,Adobe,Goldman Sachs,Tower Research,Flipkart,Uber,LinkedIn,Samsung",
      facilities: "Library,Research Labs,Hostel,WiFi Campus,Innovation Lab,Gymnasium,Cafeteria,Medical Center,Seminar Halls,Startup Incubator",
      isFeatured: false,
      isTrending: true,
      courses: [
        { name: "B.Tech Computer Science", duration: "4 Years", fees: 900000, seats: 200 },
        { name: "B.Tech Computer Science & AI", duration: "4 Years", fees: 900000, seats: 80 },
        { name: "B.Tech Computer Science & Design", duration: "4 Years", fees: 900000, seats: 50 },
        { name: "M.Tech Computer Science", duration: "2 Years", fees: 500000, seats: 50 },
      ],
      reviews: [
        { rating: 4.5, title: "CS Powerhouse", comment: "IIIT-D is a CS-focused powerhouse with excellent research and placement opportunities." },
        { rating: 4.3, title: "Great for AI/ML", comment: "If you want to work in AI/ML, IIIT-D is one of the best places in India." },
      ],
    },
  ];

  // ─── Seed Colleges ─────────────────────────────────────
  for (const collegeData of colleges) {
    const { courses, reviews, ...college } = collegeData;

    const createdCollege = await prisma.college.upsert({
      where: { slug: college.slug },
      update: {},
      create: college,
    });

    // Create courses
    for (const course of courses) {
      await prisma.course.create({
        data: {
          ...course,
          collegeId: createdCollege.id,
        },
      });
    }

    // Create reviews from demo user
    for (const review of reviews) {
      await prisma.review.create({
        data: {
          ...review,
          userId: demoUser.id,
          collegeId: createdCollege.id,
        },
      });
    }

    console.log(`✅ Seeded: ${college.name}`);
  }

  console.log("\n🎉 Database seeded successfully!");
  console.log(`📊 Total colleges: ${colleges.length}`);
  console.log(`👤 Demo account: demo@campuscompass.in / password123`);
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
